name: Build multi-OS executables

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.10]

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyautogui pyperclip

    - name: Build executable
      run: |
        pyinstaller --onefile --name Bot main.py
        # Voor macOS kan je nog --windowed erbij zetten als je geen terminal wil.

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Bot-${{ matrix.os }}
        path: dist/Bot*
